var lang = {
	"index60eed_67":"Please pass the previous level first",
	"index60eed_68":"Manhole cover elf",
	"index60eed_69":"Zombie Elves",
	"index60eed_60":"Sunshine frame",
	"index60eed_61":"Lock grid mask",
	"index60eed_62":"Grid unlock button",
	"index60eed_63":"Dave",
	"index60eed_64":"The game does not implement an interface:",
	"index60eed_65":"The game does not implement an interface:",
	"index60eed_66":"Please pass the previous level first",
	"index60eed_56":"Feature Tips",
	"index60eed_57":"Characteristic Text",
	"index60eed_58":"Synthetic light effect",
	"index60eed_59":"Start Game Box",
	"index60eed_50":"tornado",
	"index60eed_51":"Plant thumbnail layer",
	"index60eed_52":"Click on the layer",
	"index60eed_53":"progress bar",
	"index60eed_54":"Zombie Head",
	"index60eed_55":"Return button",
	"index60eed_90":"It has already been sent",
	"index60eed_91":"Not the corresponding platform",
	"index60eed_193":"Load user data",
	"index60eed_89":"Start sending tasks",
	"index60eed_194":"load resources",
	"index60eed_195":"Entering the middle",
	"index60eed_196":"--Starting to traverse data for the first time---",
	"index60eed_190":"ByteDance",
	"index60eed_191":"Start loading",
	"index60eed_192":"Configuration file loading",
	"index60eed_81":"Event ID:",
	"index60eed_82":"Event value:",
	"index60eed_83":"AB user:",
	"index60eed_84":"explain:",
	"index60eed_197":"----Enter the game from the sidebar----",
	"index60eed_85":"No such equipment, please check if the ID is correct",
	"index60eed_198":"--Start traversing data---",
	"index60eed_86":"---Sidebar judgment---",
	"index60eed_199":"---Enter from the recommendation card---",
	"index60eed_87":"Obtain the task objectives that need to be completed",
	"index60eed_88":"Not the corresponding platform",
	"index60eed_80":"Desktop icon added successfully",
	"index60eed_78":"Do you want to add a desktop",
	"index60eed_79":"Add Desktop",
	"index60eed_70":"Zombie animation",
	"index60eed_71":"Star display",
	"index60eed_72":"Luminous node",
	"index60eed_73":"Level numbers",
	"index60eed_74":"Dave",
	"index60eed_75":"Progress bar node",
	"index60eed_76":"progress bar",
	"index60eed_77":"Double Hit",
	"index60eed_292":"Within the level - Zombie Defeat",
	"index60eed_171":"Can obstacles and buffs be moved",
	"index60eed_293":"Talent - Free cultivation once",
	"index60eed_172":"Can airplanes and shells move",
	"index60eed_294":"Within the level - Primary Plant Trial",
	"index60eed_173":"Can airplanes and shells move",
	"index60eed_295":"Within the level - increase the number of primary plants",
	"index60eed_174":"Is it double the score",
	"index60eed_290":"Store - Golden Tree Seedlings",
	"index60eed_291":"Within the level - Sunshine replenishment",
	"index60eed_170":"Can obstacles and buffs be moved",
	"index60eed_179":"Node where GameController script is located",
	"index60eed_296":"Within the level - Super Plant Trial",
	"index60eed_175":"Is it double the score",
	"index60eed_297":"Settlement interface - Double Diamond Collection",
	"index60eed_176":"Node where Music Script is located",
	"index60eed_298":"Store - King Tree Seedlings",
	"index60eed_177":"Node where Music Script is located",
	"index60eed_299":"Within the level - Zombie Chest",
	"index60eed_178":"Node where GameController script is located",
	"index60eed_182":"Menu button",
	"index60eed_183":"Menu button",
	"index60eed_184":"Background music volume slider",
	"index60eed_185":"Background music volume slider",
	"index60eed_180":"Menu Node",
	"index60eed_181":"Menu Node",
	"index60eed_92":"Need to call the sendTask interface first",
	"index60eed_93":"Start subscribing",
	"index60eed_94":"Not the corresponding platform",
	"index60eed_95":"Final score:",
	"index60eed_186":"Sound effect volume slider",
	"index60eed_96":"Bullet firing rate:",
	"index60eed_187":"Sound effect volume slider",
	"index60eed_97":"Bullet firing rate: MAX",
	"index60eed_188":"Custom Components/List Items",
	"index60eed_98":"Bullet attack power:",
	"index60eed_189":"Custom Components/List",
	"index60eed_99":"fraction:",
	"index60eed_391":"The number of people who have received rewards from a certain differentiation card (open_id is the user's information, reward_index=is the reward configuration, 1-5)",
	"index60eed_270":"Number of people entering the Loading interface",
	"index60eed_392":"english",
	"index60eed_271":"Number of people who have completed loading",
	"index60eed_150":"Obstacle generation time interval",
	"index60eed_393":"Japanese",
	"index60eed_272":"Number of people arriving at the main interface",
	"index60eed_151":"The time interval for obstacle generation can be adjusted by controlling this frequency, and the final frequency is (this variable * Math. random())+(obstacle height/obstacle movement speed)",
	"index60eed_394":"traditional Chinese character",
	"index60eed_273":"Number of people who click on level 1-1",
	"index60eed_152":"Every time an obstacle is generated, the health value of the obstacle increases",
	"index60eed_390":"Number of people receiving gifts in the sidebar",
	"index60eed_399":"Double Hit",
	"index60eed_278":"Number of people entering the talent pool",
	"index60eed_157":"Bullet firing speed, in pixels per second, will increase with buff",
	"index60eed_279":"Number of people entering the equipment",
	"index60eed_158":"Projectile attack power",
	"index60eed_159":"Attack power: When a shell hits an obstacle, the health of the obstacle decreases. Eating buff will increase the health of the obstacle",
	"index60eed_395":"attack",
	"index60eed_274":"The number of people dragging plants",
	"index60eed_153":"Each time an obstacle is generated, the health value of the obstacle increases, and the final result is (this variable * Math. random)",
	"index60eed_396":"Attack speed",
	"index60eed_275":"The number of people who have successfully evolved plants",
	"index60eed_154":"Launch several shells per second",
	"index60eed_397":"Critical Strike",
	"index60eed_276":"The number of people who click to start the battle",
	"index60eed_155":"The number of shells fired per second remains constant, and when this value is too high, the device will experience a noticeable delay",
	"index60eed_398":"Explosive injury",
	"index60eed_277":"Number of people completing levels 1-1",
	"index60eed_156":"Projectile firing speed",
	"index60eed_281":"Number of people entering the store",
	"index60eed_160":"Probability of generating buff balls",
	"index60eed_282":"The number of people who have opened level x (where x is the level number)",
	"index60eed_161":"What is the probability of generating a buff ball",
	"index60eed_283":"The number of times to enter level X (where X is the level number)",
	"index60eed_162":"Buff ball related parameters",
	"index60eed_284":"End the number of people in level x (where x is the level number)",
	"index60eed_163":"How much firing rate do you increase each time you eat a buff ball? aggressivity? 0 is how much firing rate is added each time, 1 is how much attack power is added each time",
	"index60eed_280":"The number of people entering the plant",
	"index60eed_289":"Gold Coin Bar - Get Gold Coins",
	"index60eed_168":"Can shells be fired",
	"index60eed_169":"Can shells be fired? If false, the aircraft will no longer fire shells",
	"index60eed_285":"The number of times to end level x (where x is the level number)",
	"index60eed_164":"Whether to debug or not",
	"index60eed_286":"The number of people who won the Xth level (x is the level number)",
	"index60eed_165":"If enabled, some collision shapes will be drawn",
	"index60eed_287":"The number of people who failed level x (where x is the level number)",
	"index60eed_166":"Whether to generate obstacles",
	"index60eed_288":"Diamond Bar - Get Diamonds",
	"index60eed_167":"Whether to generate obstacles",
	"index60eed_139":"What is the minimum and maximum distance range between each obstacle",
	"index60eed_490":"Attack speed",
	"index60eed_491":"Critical Strike",
	"index60eed_370":"Within the level - Zombie Chest",
	"index60eed_492":"Explosive injury",
	"index60eed_371":"Main interface -7-day check-in",
	"index60eed_250":"The switch is not configured. Please configure it on PlatformManagerial. ts",
	"index60eed_493":"Double Hit",
	"index60eed_372":"Main interface - Plant Treasure Box",
	"index60eed_251":"Start recording screen",
	"index60eed_130":"Buff ball preform",
	"index60eed_498":"Composite button",
	"index60eed_377":"Within the level - the number of times a player obtains a super plant pop-up window x plants",
	"index60eed_256":"Clicked the button",
	"index60eed_135":"The left coordinate of the projectile is generated, and the position of the projectile is established in the coordinate system with the aircraft anchor point as the origin",
	"index60eed_499":"Equipment attribute pop-up layer",
	"index60eed_378":"Store interface - Number of times to use diamonds to extract ordinary saplings",
	"index60eed_257":"Fingers moved on the screen",
	"index60eed_136":"The projectile generates coordinates on the right side",
	"index60eed_379":"Talent - Number of times to upgrade talent using coins",
	"index60eed_258":"particle",
	"index60eed_137":"The right coordinate of the shell is generated, and the position of the shell is established with the aircraft anchor point as the origin when establishing a coordinate system",
	"index60eed_259":"Particle Node",
	"index60eed_138":"Range of distance between each obstacle",
	"index60eed_494":"Equipment backpack",
	"index60eed_373":"Summer Celebration - Claim Again",
	"index60eed_252":"Pause screen recording",
	"index60eed_131":"Buff ball preform",
	"index60eed_495":"Already equipped layer",
	"index60eed_374":"Within the level - the number of people who used the y-th Sunshine Supplement in level x (only counting the first 5 times)",
	"index60eed_253":"Re record the screen",
	"index60eed_132":"Text displaying invincible remaining time",
	"index60eed_496":"Equipment attributes",
	"index60eed_375":"Within the level - the number of people who used the y-th zombie defeat in level x (only counting the first 10)",
	"index60eed_254":"Initialize score",
	"index60eed_133":"Text displaying invincible remaining time",
	"index60eed_497":"One click equipment",
	"index60eed_376":"Within the level - the number of times the super plant pop-up window displays x plants",
	"index60eed_255":"Highest score in history:",
	"index60eed_134":"The left coordinate of the shell generation",
	"index60eed_380":"Store interface - Number of times to obtain the King's sapling (only counting the first 5 times)",
	"index60eed_381":"Main interface - Number of people checked in on the Xth day",
	"index60eed_260":"Start Game Button",
	"index60eed_382":"Main interface - Number of people who checked in on the Xth day and clicked to collect again",
	"index60eed_261":"Start Game Button",
	"index60eed_140":"Invincible duration",
	"index60eed_383":"Summer Celebration - Number of people unlocking the Xth reward",
	"index60eed_262":"Display the highest scoring text in history",
	"index60eed_141":"Invincibility duration, how long does it take to recover when the invincibility button is pressed",
	"index60eed_388":"Number of successful followers",
	"index60eed_267":"Hours ago",
	"index60eed_146":"Initial health value of obstacles",
	"index60eed_389":"Number of successful subscribers",
	"index60eed_268":"Minutes ago",
	"index60eed_147":"The initial health value of an obstacle is actually the numerical value of the text on the obstacle. When the value is 0, the obstacle is destroyed. However, this value is not the initial health value of the final obstacle, as the final initial value also includes a random number, as detailed in the Barrier script",
	"index60eed_269":"A second ago",
	"index60eed_148":"Obstacle movement speed",
	"index60eed_149":"What is the speed of obstacle movement in pixels per second",
	"index60eed_384":"Summer Celebration - Number of people receiving the Xth reward",
	"index60eed_263":"Display the highest scoring text in history",
	"index60eed_142":"Obstacle width (required)",
	"index60eed_385":"Summer Celebration - Number of people who choose to receive the Xth reward again",
	"index60eed_264":"Click button sound effect",
	"index60eed_143":"Obstacle width (required), the code will calculate the optimal position for obstacle generation based on this value",
	"index60eed_386":"The number of times to enter level X (where X is the level number)",
	"index60eed_265":"Click button sound effect",
	"index60eed_144":"Obstacle height (required)",
	"index60eed_387":"The number of times to end level x (where x is the level number)",
	"index60eed_266":"Days ago",
	"index60eed_145":"Obstacle height (required), the code will calculate the optimal position for obstacle generation based on this value",
	"index60eed_359":"Diamond Bar - Get Diamonds",
	"index60eed_238":"No such equipment, please check if the ID is correct",
	"index60eed_117":"All obstacle parent nodes, this node is used to eliminate all obstacles",
	"index60eed_239":"Load bundle:",
	"index60eed_118":"Resurrection button",
	"index60eed_119":"Resurrection button, clicking the resurrection button once will hide it",
	"index60eed_590":"Attack:",
	"index60eed_591":"Attack speed:",
	"index60eed_470":"orange",
	"index60eed_592":"0",
	"index60eed_471":"orange",
	"index60eed_350":"Number of players entering the game on the 4th day",
	"index60eed_597":"Plant strips",
	"index60eed_476":"Double Hit",
	"index60eed_355":"The number of people who have opened level x (where x is the level number)",
	"index60eed_234":"How many more times can the text be used to display item buttons",
	"index60eed_113":"Nodes displayed at the end of the game",
	"index60eed_598":"Consuming sunlight",
	"index60eed_477":"Remove it",
	"index60eed_356":"End the number of people in level x (where x is the level number)",
	"index60eed_235":"How many more times can the text be used to display item buttons",
	"index60eed_114":"Airplane (protagonist)",
	"index60eed_599":"Attribute Text",
	"index60eed_478":"equipment",
	"index60eed_357":"The number of people who won the Xth level (x is the level number)",
	"index60eed_236":"How many times can the prop button be used?",
	"index60eed_115":"The protagonist, also known as the airplane node",
	"index60eed_479":"equipment",
	"index60eed_358":"The number of people who failed level x (where x is the level number)",
	"index60eed_237":"How many times can the prop button be used?",
	"index60eed_116":"All obstacle parent nodes",
	"index60eed_593":"Life:",
	"index60eed_472":"attack",
	"index60eed_351":"Number of players entering the game on the 5th day",
	"index60eed_230":"User Agreement Policy (Plant Variation Recruitment Version)",
	"index60eed_594":"Plant Description",
	"index60eed_473":"Attack speed",
	"index60eed_352":"Number of players entering the game on the 6th day",
	"index60eed_231":"Loading error% s",
	"index60eed_110":"Display double score label",
	"index60eed_595":"Upgrade button",
	"index60eed_474":"Critical Strike",
	"index60eed_353":"Number of players entering the game on the 7th day",
	"index60eed_232":"Prop button",
	"index60eed_111":"Display double score label",
	"index60eed_596":"Return button",
	"index60eed_475":"Explosive injury",
	"index60eed_354":"Number of people successfully added to the desktop",
	"index60eed_233":"Prop button",
	"index60eed_112":"Nodes displayed at the end of the game",
	"index60eed_249":"Ad playback failed",
	"index60eed_128":"Prefabricated obstacles",
	"index60eed_9":"Diamond+",
	"index60eed_129":"Prefabricated obstacles",
	"index60eed_7":"non-existent",
	"index60eed_8":"Gold coins+",
	"index60eed_480":"Remove it",
	"index60eed_481":"arms",
	"index60eed_360":"Gold Coin Bar - Get Gold Coins",
	"index60eed_482":"ornaments",
	"index60eed_361":"Store - Golden Tree Seedlings",
	"index60eed_240":"Please provide the specific resource type, which cannot be the base class asset. Path:",
	"index60eed_487":"Equipment attribute pop-up window",
	"index60eed_366":"Within the level - increase the number of primary plants",
	"index60eed_245":"Scale minimum value",
	"index60eed_124":"Display status text",
	"index60eed_5":"non-existent",
	"index60eed_488":"Black screen background",
	"index60eed_367":"Within the level - Super Plant Trial",
	"index60eed_246":"Zoom maximum value",
	"index60eed_125":"Display status text, showing firing rate, attack power, regardless of the front or back position of the two labels",
	"index60eed_6":"non-existent",
	"index60eed_489":"attack",
	"index60eed_368":"Settlement interface - Double Diamond Collection",
	"index60eed_247":"Rolling items",
	"index60eed_126":"Prefabricated projectile",
	"index60eed_3":"non-existent",
	"index60eed_369":"Store - King Tree Seedlings",
	"index60eed_248":"Play advertisement",
	"index60eed_127":"Prefabricated shells, planes are constantly firing shells",
	"index60eed_4":"non-existent",
	"index60eed_483":"Helmet",
	"index60eed_362":"Within the level - Sunshine replenishment",
	"index60eed_241":"Sliding direction",
	"index60eed_1":"Sound effects not configured:",
	"index60eed_120":"Special button node",
	"index60eed_484":"clothes",
	"index60eed_363":"Within the level - Zombie Defeat",
	"index60eed_242":"Node interval",
	"index60eed_121":"Special button nodes, which are respectively \"All Elimination Invincible\" and \"Menu\"",
	"index60eed_2":"non-existent",
	"index60eed_485":"trousers",
	"index60eed_364":"Talent - Free cultivation once",
	"index60eed_243":"Moving speed",
	"index60eed_122":"Display score text",
	"index60eed_486":"shoes",
	"index60eed_365":"Within the level - Primary Plant Trial",
	"index60eed_244":"Deceleration frequency",
	"index60eed_123":"Text displaying scores",
	"index60eed_579":"The current fragments are insufficient",
	"index60eed_458":"Equipment attribute pop-up layer",
	"index60eed_337":"Within the level - the number of times the encyclopedia is viewed",
	"index60eed_216":"Corn missile",
	"index60eed_459":"Composite special effects",
	"index60eed_338":"Number of people unlocking the Xth plant position within the level (X is 1-5)",
	"index60eed_217":"Trigger kill effect",
	"index60eed_339":"Within the level - the number of people who unlock the Xth plant position in level Y (X is 1-5, Y is the level number)",
	"index60eed_218":"Unable to find 4399HTML5 API",
	"index60eed_219":"Plant Variation Tips Edition",
	"index60eed_23":"Gold coin label",
	"index60eed_24":"Successfully opened the mysterious treasure chest",
	"index60eed_690":"Description modification",
	"index60eed_25":"Successfully opened the mysterious treasure chest",
	"index60eed_691":"Description modification",
	"index60eed_570":"Plant Bar List",
	"index60eed_26":"Formation plant layer",
	"index60eed_27":"Beijing",
	"index60eed_28":"Shanghai",
	"index60eed_29":"Guangzhou",
	"index60eed_696":"Fly from top to bottom",
	"index60eed_575":"title",
	"index60eed_454":"Already equipped layer",
	"index60eed_333":"New Talent - The current highest number of people who have activated the Xth talent using diamonds through level Y (X is the talent ID, Y is the level number)",
	"index60eed_212":"Charging in",
	"index60eed_697":"Nodes that fly from top to bottom",
	"index60eed_576":"Characteristic Text",
	"index60eed_455":"Synthetic equipment",
	"index60eed_334":"Store - The current highest number of times a golden sapling is extracted when passing level X (X is the level number)",
	"index60eed_213":"Cooling in progress",
	"index60eed_698":"Fly from top to bottom, how far is it from the top of the screen",
	"index60eed_577":"The current plant is at full level",
	"index60eed_456":"One click synthesis",
	"index60eed_335":"Plant Interface - Number of people upgrading plants to level X",
	"index60eed_214":"No zombies within the attack range",
	"index60eed_699":"Fly from top to bottom, how far is it from the top of the screen",
	"index60eed_578":"Unlock",
	"index60eed_457":"Composite button",
	"index60eed_336":"Store - The current highest number of times the King Tree has been fully extracted at level X (where X is the level number)",
	"index60eed_215":"---Plants die---",
	"index60eed_692":"Description modification",
	"index60eed_571":"Synthesizable route",
	"index60eed_450":"3 pieces of equipment with the same name can be combined",
	"index60eed_693":"Description modification",
	"index60eed_572":"Plant strips",
	"index60eed_451":"Already equipped",
	"index60eed_330":"New Talent - Number of people using gold coins to activate X talent (X is the talent ID)",
	"index60eed_20":"Open animation",
	"index60eed_694":"Description modification",
	"index60eed_573":"Plant strips",
	"index60eed_452":"This equipment has reached the highest level of quality",
	"index60eed_331":"New Talent - Number of people using diamonds to activate the Xth talent (where X is the talent ID)",
	"index60eed_210":"Button sound effects",
	"index60eed_21":"Gold Coin Box",
	"index60eed_695":"Description modification",
	"index60eed_574":"return",
	"index60eed_453":"Equipment backpack",
	"index60eed_332":"New Talent - The current highest number of people who have activated X Talent with gold coins through level Y (where X is the talent ID and Y is the level number)",
	"index60eed_211":"All zombies have been eliminated",
	"index60eed_22":"Gold Coin Chart",
	"index60eed_469":"Purple;",
	"index60eed_348":"Number of players entering the game on the second day",
	"index60eed_227":"Privacy protection policy - Kwai games (plant variation version)",
	"index60eed_106":"Breaking the record!",
	"index60eed_349":"Number of players entering the game on the third day",
	"index60eed_228":"Privacy Protection Policy (Plant Variation Recruitment Edition)",
	"index60eed_107":"Breaking the record!",
	"index60eed_229":"User agreement policy - Kwai games (plant variation version)",
	"index60eed_108":"Display the label of buff type obtained",
	"index60eed_109":"Display the label of buff type obtained",
	"index60eed_12":"Do you need to cache resources",
	"index60eed_13":"There is data available",
	"index60eed_580":"upgrade",
	"index60eed_14":"-There are archives available locally-",
	"index60eed_581":"upgrade",
	"index60eed_460":"Equipment column base map",
	"index60eed_15":"Upload once a minute to the server",
	"index60eed_16":"The avatar came in:",
	"index60eed_17":"Avatar download successful:",
	"index60eed_18":"Do you need caching",
	"index60eed_19":"Note: Only bg and root are required under the main node",
	"index60eed_586":"Not open",
	"index60eed_465":"green",
	"index60eed_344":"Within the level - the number of times the player uses X quality weapons (X is the quality ID)",
	"index60eed_223":"User type:",
	"index60eed_102":"Bullet firing rate increase",
	"index60eed_587":"upgrade",
	"index60eed_466":"blue",
	"index60eed_345":"Store interface - Number of times to use diamonds to extract regular equipment",
	"index60eed_224":"Entering channel judgment",
	"index60eed_103":"Bullet attack power enhancement",
	"index60eed_588":"Unlock",
	"index60eed_467":"blue",
	"index60eed_346":"Store - The current highest number of times a gold can is drawn when reaching level X (where X is the level number)",
	"index60eed_225":"Compile",
	"index60eed_104":"game over",
	"index60eed_589":"Type:",
	"index60eed_468":"Purple;",
	"index60eed_347":"Number of players entering the game on the first day",
	"index60eed_226":"User type:",
	"index60eed_105":"Final score:",
	"index60eed_582":"Congratulations on unlocking a new plant!",
	"index60eed_461":"left arrow",
	"index60eed_340":"Equipment - Number of times synthesis is used",
	"index60eed_583":"Not open",
	"index60eed_462":"Right arrow",
	"index60eed_341":"Equipment - Number of times to use one click synthesis",
	"index60eed_220":"Plant Evolution Invincible Edition",
	"index60eed_584":"Nut Strong",
	"index60eed_463":"white",
	"index60eed_342":"Equipment - Number of people wearing X pieces of equipment (up to a maximum of 6)",
	"index60eed_221":"Potato hyperevolution",
	"index60eed_100":"fraction:",
	"index60eed_10":"Text displaying numerical values",
	"index60eed_585":"0",
	"index60eed_464":"green",
	"index60eed_343":"Equipment - The highest number of people who possess equipment of quality X (where X is the quality ID)",
	"index60eed_222":"Plant Variation Tips Edition",
	"index60eed_101":"fraction:",
	"index60eed_11":"Text displaying numerical values",
	"index60eed_319":"Within the level - the player increases the number of y plants in level x",
	"index60eed_678":"Medium size",
	"index60eed_557":"Free upgrade button",
	"index60eed_436":"Get button",
	"index60eed_315":"Within the level - the number of people who used the y-th zombie defeat in level x (only counting the first 10)",
	"index60eed_679":"large",
	"index60eed_558":"Total number of training sessions",
	"index60eed_437":"S win",
	"index60eed_316":"Within the level - the number of times the super plant pop-up window displays x plants",
	"index60eed_559":"Cultivation consumption",
	"index60eed_438":"<",
	"index60eed_317":"Within the level - the number of times a player obtains a super plant pop-up window x plants",
	"index60eed_439":"Start the game",
	"index60eed_318":"Within the level - the number of times the player tries the y plant in level x",
	"index60eed_45":"Zombie layer",
	"index60eed_46":"Bullet layer",
	"index60eed_47":"Summoning layer",
	"index60eed_48":"Special effects layer",
	"index60eed_49":"Recycling bucket",
	"index60eed_674":"auxiliary",
	"index60eed_553":"Talent Display",
	"index60eed_432":"Numerical changes",
	"index60eed_311":"Online duration up to 15m",
	"index60eed_675":"special",
	"index60eed_554":"Talent Description",
	"index60eed_433":"Did you draw plants or fragments",
	"index60eed_312":"Online duration reaches 20m",
	"index60eed_676":"small-scale",
	"index60eed_555":"Return button",
	"index60eed_434":"Numerical changes",
	"index60eed_313":"All (new and old) users start the game",
	"index60eed_677":"medium-sized",
	"index60eed_556":"Upgrade button",
	"index60eed_435":"Cancel button",
	"index60eed_314":"Within the level - the number of people who used the y-th Sunshine Supplement in level x (only counting the first 5 times)",
	"index60eed_40":"try now ",
	"index60eed_670":"Do you need to click on the special effects",
	"index60eed_41":"---The Last Wave---",
	"index60eed_671":"shooter",
	"index60eed_550":"All talents have reached their full level",
	"index60eed_42":"---Game over, victory in battle----",
	"index60eed_672":"pitcher",
	"index60eed_551":"Extracting talent",
	"index60eed_430":"Obtain fragments",
	"index60eed_43":"Destruction of Treasure Box 2",
	"index60eed_673":"trap",
	"index60eed_552":"Full level",
	"index60eed_431":"Level promotion display",
	"index60eed_310":"Online duration up to 12m",
	"index60eed_44":"Formation plant layer",
	"index60eed_209":"Button sound effects",
	"index60eed_689":"Description modification",
	"index60eed_568":"win",
	"index60eed_447":"Synthesis successful, co synthesis",
	"index60eed_326":"Main interface - Number of people obtained from the Plant Treasure Box in level X",
	"index60eed_205":"Collision sound effects",
	"index60eed_569":"open",
	"index60eed_448":"second",
	"index60eed_327":"Summer Celebration - Number of people unlocking the Xth reward",
	"index60eed_206":"Collision sound effects",
	"index60eed_449":"No synthesizable equipment",
	"index60eed_328":"Summer Celebration - Number of people receiving the Xth reward",
	"index60eed_207":"Buff sound effect",
	"index60eed_329":"Summer Celebration - Number of people who choose to receive the Xth reward again",
	"index60eed_208":"Buff sound effect",
	"index60eed_34":"try now ",
	"index60eed_35":"One more",
	"index60eed_36":"Nut Strong",
	"index60eed_680":"Large scale",
	"index60eed_37":"Superheroes cannot be recycled",
	"index60eed_38":"Before reaching the formation area, directly put it back into the object pool",
	"index60eed_39":"The current plant cannot evolve",
	"index60eed_685":"/Medium body type",
	"index60eed_564":"Closing failed",
	"index60eed_443":"Star rating reminder",
	"index60eed_322":"Store interface - Number of times to obtain the King's sapling (only counting the first 5 times)",
	"index60eed_201":"As you are a minor, you can only play for one hour",
	"index60eed_686":"/Large body type",
	"index60eed_565":"Closing failed 2",
	"index60eed_444":"Sunshine layer",
	"index60eed_323":"Main interface - Number of people checked in on the Xth day",
	"index60eed_202":"I",
	"index60eed_687":"Life:",
	"index60eed_566":"Closing failed 1",
	"index60eed_445":"Sunshine icon",
	"index60eed_324":"Main interface - Number of people who checked in on the Xth day and clicked to collect again",
	"index60eed_203":"background music",
	"index60eed_688":"Attack:",
	"index60eed_567":"Effect X",
	"index60eed_446":"Increase sunshine",
	"index60eed_325":"Main interface - Number of people appearing in the Plant Treasure Box in level X",
	"index60eed_204":"background music",
	"index60eed_681":"single",
	"index60eed_560":"UI not configured:",
	"index60eed_30":"Shenzhen",
	"index60eed_682":"1 grid range",
	"index60eed_561":"",
	"index60eed_440":"Plant Catalog",
	"index60eed_31":"Other situations can be cleared",
	"index60eed_683":"3 grid range",
	"index60eed_562":"non-existent",
	"index60eed_441":"Sunshine quantity",
	"index60eed_320":"Store interface - Number of times to use diamonds to extract ordinary saplings",
	"index60eed_32":"---Trigger death effect----",
	"index60eed_684":"/Small body size",
	"index60eed_563":"Already exists",
	"index60eed_442":"Zombie Tip",
	"index60eed_321":"Talent - Number of times to upgrade talent using coins",
	"index60eed_200":"---Enter from the recommendation card---",
	"index60eed_33":"Drag the deployed plants to the recycling bin to return sunlight and the number of times they can be placed",
	"index60eed_539":"Battle Command Button",
	"index60eed_418":"lower",
	"index60eed_419":"<outline color=#3d240a width=4><color=#fffff9><size=52>Next must win</c><color=#db3cf8><size=72>epic</color><color=#fffff9><size=52>equipment</c></outline>",
	"index60eed_656":"0",
	"index60eed_535":"Store button",
	"index60eed_414":"Convert to",
	"index60eed_657":"0",
	"index60eed_536":"Plant button",
	"index60eed_415":"individual",
	"index60eed_658":"Life:",
	"index60eed_537":"Set button",
	"index60eed_416":"Congratulations on obtaining a new plant",
	"index60eed_659":"Plant name",
	"index60eed_538":"Check in button",
	"index60eed_417":"Congratulations on obtaining a new plant",
	"index60eed_652":"Attribute Display",
	"index60eed_531":"Unlock",
	"index60eed_410":"Nut Strong",
	"index60eed_653":"Type:",
	"index60eed_532":"win",
	"index60eed_411":"free",
	"index60eed_654":"Attack:",
	"index60eed_533":"Desktop icon added successfully",
	"index60eed_412":"get",
	"index60eed_655":"Attack speed:",
	"index60eed_534":"Talent button",
	"index60eed_413":"individual",
	"index60eed_650":"Get button",
	"index60eed_651":"Description modification",
	"index60eed_530":"Unlock",
	"index60eed_429":"Result Display",
	"index60eed_308":"Online duration up to 7m",
	"index60eed_309":"Online duration up to 10m",
	"index60eed_667":"---Subscription Return---",
	"index60eed_546":"Not open",
	"index60eed_425":"Lottery again",
	"index60eed_304":"Store - Gold Jars",
	"index60eed_668":"----Subscribe and save locally-----",
	"index60eed_547":"<outline color=#3d240a width=4><color=#fffff9>Cultivated</c><color=#46f700>",
	"index60eed_426":"Lottery results",
	"index60eed_305":"Online duration up to 1m",
	"index60eed_669":"---Subscribe and save locally---",
	"index60eed_548":"</color><color=#fffff9>times</c></outline>",
	"index60eed_427":"Ordinary lottery",
	"index60eed_306":"Online duration up to 3m",
	"index60eed_549":"Extracting talent",
	"index60eed_428":"Golden Lottery",
	"index60eed_307":"Online duration up to 5m",
	"index60eed_663":"Layout nodes",
	"index60eed_542":"Sidebar gift button",
	"index60eed_421":"Nut Strong",
	"index60eed_300":"Main interface -7-day check-in",
	"index60eed_664":"written words",
	"index60eed_543":"Add desktop button",
	"index60eed_422":"Life:",
	"index60eed_301":"Main interface - Plant Treasure Box",
	"index60eed_665":"--Initiate subscription--",
	"index60eed_544":"Extracting talent",
	"index60eed_423":"Attack:",
	"index60eed_302":"Summer Celebration - Claim Again",
	"index60eed_666":"---Initiate subscription---",
	"index60eed_545":"Full level",
	"index60eed_424":"Result Display",
	"index60eed_303":"Within the level - Unlock the location of plants",
	"index60eed_660":"Attribute Text",
	"index60eed_661":"Consuming sunlight",
	"index60eed_540":"Follow button",
	"index60eed_662":"close button",
	"index60eed_541":"Equipment button",
	"index60eed_420":"<outline color=#3d240a width=4><color=#fffff9><size=52>Next must win</c><color=#ff9333><size=72>Legend</color><color=#fffff9><size=52>Equipment</c></outline>",
	"index60eed_638":"Please enter the game from the sidebar first",
	"index60eed_517":"Add Desktop",
	"index60eed_639":"Cancel button",
	"index60eed_518":"Resource",
	"index60eed_519":"Repel",
	"index60eed_634":"Task steps:",
	"index60eed_513":"Background lighting",
	"index60eed_635":"】Enter the game",
	"index60eed_514":"Share button",
	"index60eed_636":"I have already received the reward",
	"index60eed_515":"Confirm button",
	"index60eed_637":"---Receive Sidebar Gift Pack---",
	"index60eed_516":"Double Get Button",
	"index60eed_630":"Sound effects",
	"index60eed_631":"close button",
	"index60eed_510":"Obtain the number of stars",
	"index60eed_632":"Version Text",
	"index60eed_511":"Obtain star condition display",
	"index60eed_633":"Privacy Policy",
	"index60eed_512":"Get rewards",
	"index60eed_649":"Cancel button",
	"index60eed_528":"----Enable sliding function-----",
	"index60eed_407":"Equipment icon",
	"index60eed_529":"----Sliding function-----",
	"index60eed_408":"Numerical changes",
	"index60eed_409":"lower",
	"index60eed_645":"Successfully watched advertisement, progress+1",
	"index60eed_524":"Cancel button",
	"index60eed_403":"Obtain fragments",
	"index60eed_646":"0",
	"index60eed_525":"Get button",
	"index60eed_404":"Bottom frame",
	"index60eed_647":"Plant images",
	"index60eed_526":"Title Text",
	"index60eed_405":"Equipment icon",
	"index60eed_648":"bright",
	"index60eed_527":"----Click on the function to enable-----",
	"index60eed_406":"Equipment reinforcement",
	"index60eed_641":"Task Text",
	"index60eed_520":"Insufficient gold coin acquisition attempts today",
	"index60eed_642":"Show pictures",
	"index60eed_521":"The number of diamond acquisitions today is insufficient",
	"index60eed_400":"Result Display",
	"index60eed_643":"Not showing up at the check-in time",
	"index60eed_522":"The number of tornadoes in this level is insufficient",
	"index60eed_401":"Lottery results",
	"index60eed_644":"Successfully watched advertisement, progress+1",
	"index60eed_523":"Get resource display",
	"index60eed_402":"Result Display",
	"index60eed_640":"Get button",
	"index60eed_737":"Taiwan",
	"index60eed_616":"Ordinary lottery",
	"index60eed_738":"Hong Kong",
	"index60eed_617":"Golden Lottery",
	"index60eed_739":"Macao",
	"index60eed_618":"Return button",
	"index60eed_619":"King's Lottery",
	"index60eed_733":"Gansu Province",
	"index60eed_612":"free",
	"index60eed_734":"Qinghai",
	"index60eed_613":"---Draw items---",
	"index60eed_735":"Ningxia",
	"index60eed_614":"lower",
	"index60eed_736":"Xinjiang",
	"index60eed_615":"lower",
	"index60eed_730":"Yunnan",
	"index60eed_731":"Xizang",
	"index60eed_610":"free",
	"index60eed_732":"Shaanxi",
	"index60eed_611":"<outline color=#3d240a width=4><color=#46f701><size=72></color></outline>",
	"index60eed_627":"Ordinary lottery",
	"index60eed_506":"Result Display",
	"index60eed_628":"Golden Lottery",
	"index60eed_507":"arrange arms and embattle",
	"index60eed_629":"background music",
	"index60eed_508":"Upgrade Plants",
	"index60eed_509":"Upgrade Talent",
	"index60eed_744":"-----Game over, battle failed-----",
	"index60eed_623":"Equipment lottery button layer",
	"index60eed_502":"6 Lv Qiang",
	"index60eed_624":"Switch button layer",
	"index60eed_503":"Random 10",
	"index60eed_625":"Plant Lottery Button",
	"index60eed_504":"S win",
	"index60eed_626":"Equipment lottery button",
	"index60eed_505":"<",
	"index60eed_740":"abroad",
	"index60eed_741":"existence",
	"index60eed_620":"King's Lottery Button",
	"index60eed_742":"Login failed!",
	"index60eed_621":"The number of times advertisements are viewed in the King's Lottery",
	"index60eed_500":"Equipment column base map",
	"index60eed_743":"------All zombies have been killed in action-----",
	"index60eed_622":"Plant Lottery Button Layer",
	"index60eed_501":"Full gold equipment",
	"index60eed_715":"Jiangsu",
	"index60eed_716":"Zhejiang",
	"index60eed_717":"Anhui Province",
	"index60eed_718":"Fujian",
	"index60eed_711":"Liaoning",
	"index60eed_712":"Jilin",
	"index60eed_713":"Heilongjiang Province",
	"api_2":"The current address is not in the 4399 domain, which may cause some API interfaces to generate exceptions.",
	"index60eed_714":"Shanghai",
	"api_1":"Player ad failed======Test environment callback directly",
	"index60eed_719":"Jiangxi",
	"index60eed_710":"Inner Mongolia",
	"index60eed_726":"Hainan",
	"index60eed_605":"Unlock",
	"index60eed_727":"Chongqing",
	"index60eed_606":"win",
	"index60eed_728":"Sichuan",
	"index60eed_607":"Advertisement successfully played, progress+1",
	"index60eed_729":"Guizhou",
	"index60eed_608":"Extracting plants",
	"index60eed_722":"Hubei Province",
	"index60eed_601":"Upgrade consumption",
	"index60eed_723":"Hunan",
	"index60eed_602":"Characteristic Text",
	"index60eed_724":"Guangdong",
	"index60eed_603":"Plant name",
	"index60eed_725":"Guangxi",
	"index60eed_604":"Upgrade consumption",
	"index60eed_609":"lower",
	"index60eed_720":"Shandong",
	"index60eed_721":"Henan",
	"index60eed_600":"Display plants",
	"index60eed_704":"Fly from left to right",
	"index60eed_705":"Nodes flying from left to right",
	"index60eed_706":"Beijing",
	"index60eed_707":"Tianjin",
	"index60eed_700":"Fly from bottom to top",
	"index60eed_701":"Nodes flying from bottom to top",
	"index60eed_702":"Fly from bottom to top, how far is it from the bottom of the screen",
	"index60eed_703":"Fly from bottom to top, how far is it from the bottom of the screen",
	"index60eed_708":"Hebei Province",
	"index60eed_709":"Shanxi"
}
